name: SonarQube Analysis

on:
  push:
    branches:
      - main  # Əgər sən başqa branch istifadə edirsənsə, onu yaz
  pull_request:
    branches:
      - main

jobs:
  sonar:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'

      - name: Run SonarQube scanner
        run: |
          curl -sSLo sonar-scanner-cli-linux.zip https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.6.2.2472-linux.zip
          unzip sonar-scanner-cli-linux.zip
          ./sonar-scanner-4.6.2.2472-linux/bin/sonar-scanner \
            -Dsonar.projectKey=my-node-project \
            -Dsonar.sources=src \
            -Dsonar.host.url=http://localhost:9000
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
